# Kustomization for Lucrum ArgoCD deployment
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lucrum

resources:
  - namespace.yaml
  - web-deployment.yaml
  - pdb.yaml
  - hpa.yaml
  - cron-paper-mtm.yaml
  - cron-klines-update.yaml

commonLabels:
  app.kubernetes.io/part-of: lurus
  app.kubernetes.io/managed-by: argocd
