/**
 * Academic Strategy Templates
 * 学术策略模板
 *
 * Strategies based on peer-reviewed academic research and financial economics papers.
 * Each strategy includes citations to the original research.
 *
 * @module lib/strategy-templates/academic
 */

import type { StrategyTemplate } from "./index";

// =============================================================================
// ACADEMIC STRATEGIES / 学术策略 (10个)
// =============================================================================

export const academicStrategies: StrategyTemplate[] = [
  // ========== MOMENTUM STRATEGIES (3) ==========
  {
    id: "academic-01",
    name: "Jegadeesh-Titman动量策略",
    nameEn: "Jegadeesh-Titman Momentum",
    category: "momentum",
    subcategory: "cross-sectional",
    type: "academic",
    icon: "🎓",
    summary: "12个月收益率排序，买入赢家卖出输家，经典动量异象",
    summaryEn:
      "12-month return ranking, buy winners sell losers, classic momentum anomaly",
    description:
      "Jegadeesh和Titman在1993年发现的动量效应：过去12个月表现好的股票在未来3-12个月继续表现好。这一发现挑战了有效市场假说，成为行为金融学的重要证据。",
    markets: ["stock"],
    timeframes: ["position", "longterm"],
    difficulty: 2,
    riskLevel: "medium",
    theory: {
      origin: "1993年《Journal of Finance》发表",
      author: "Narasimhan Jegadeesh & Sheridan Titman",
      authorInfo:
        "Jegadeesh是Emory大学金融学教授，Titman是德克萨斯大学奥斯汀分校教授",
      year: 1993,
      paper: "Returns to Buying Winners and Selling Losers",
      paperUrl: "https://doi.org/10.1111/j.1540-6261.1993.tb04702.x",
      academicBasis: "行为金融学、投资者反应不足",
    },
    logic: {
      entry: [
        "计算所有股票过去12个月的收益率",
        "跳过最近1个月（避免短期反转）",
        "买入收益率排名前10%的股票",
      ],
      exit: ["持有3-12个月后卖出", "或收益率排名跌出前30%时卖出"],
      positionSizing: "等权重分配到入选股票",
      riskManagement: "分散投资至少20只股票",
    },
    params: [
      {
        name: "回望期",
        nameEn: "Lookback Period",
        default: 12,
        range: "6-12",
        description: "计算收益的月数",
      },
      {
        name: "跳过期",
        nameEn: "Skip Period",
        default: 1,
        range: "0-1",
        description: "跳过最近几个月避免短期反转",
      },
      {
        name: "持有期",
        nameEn: "Holding Period",
        default: 6,
        range: "3-12",
        description: "持有月数",
      },
      {
        name: "选股比例",
        nameEn: "Selection Ratio",
        default: "10%",
        range: "5-20%",
        description: "选取排名前X%的股票",
      },
    ],
    pros: [
      "学术验证有效，大量实证研究支持",
      "逻辑简单，易于实现",
      "在全球多个市场有效",
    ],
    cons: [
      "偶尔经历'动量崩溃'（如2009年）",
      "交易成本可能侵蚀收益",
      "需要足够多的股票形成组合",
    ],
    bestPractices: {
      dos: [
        "跳过最近1个月的收益以避免短期反转",
        "分散投资多只股票",
        "定期再平衡（月度或季度）",
      ],
      donts: [
        "不要在市场大跌后立即使用",
        "不要集中持有少数股票",
        "不要忽视交易成本",
      ],
      tips: [
        "可与价值因子结合使用以分散风险",
        "在牛市中效果更好",
        "考虑使用风险调整后的动量",
      ],
      commonMistakes: [
        "不跳过最近1个月导致短期反转拖累",
        "选股数量太少导致集中度过高",
        "再平衡频率不当",
      ],
    },
    periodSignificance: {
      shortTerm: "1-3个月动量可能反转",
      mediumTerm: "3-12个月动量效应最强",
      longTerm: "12个月以上可能出现长期反转",
      bestPeriod: "6-12个月回望，3-6个月持有",
    },
    bestFor: "牛市中的个股选择",
    bestForEn: "Stock selection in bull markets",
    notSuitableFor: "熊市反弹初期、流动性危机期间",
    historicalPerformance: {
      backtestPeriod: "1965-1989 (原始论文)",
      annualReturn: 12,
      maxDrawdown: 30,
      sharpeRatio: 0.6,
      winRate: 55,
      note: "年化超额收益约1%/月",
    },
    relatedStrategies: ["academic-02", "academic-06"],
    riskWarning:
      "动量策略在市场反转时可能遭受重大损失，2009年3月动量策略回撤超过40%。",
    prompt:
      "Jegadeesh-Titman动量策略：计算过去11个月收益（跳过最近1月），买入排名前10%的股票，持有6个月后再平衡",
    version: "1.0",
    lastUpdated: "2025-01-20",
  },
  {
    id: "academic-02",
    name: "Moskowitz时间序列动量",
    nameEn: "Time Series Momentum (TSMOM)",
    category: "momentum",
    subcategory: "time-series",
    type: "academic",
    icon: "📊",
    summary: "单一资产自身的动量，过去12个月正收益则做多",
    summaryEn: "Single asset's own momentum, long if positive 12-month return",
    description:
      "Moskowitz、Ooi和Pedersen在2012年发现时间序列动量在期货市场广泛存在：如果一个资产过去12个月收益为正，则未来倾向于继续上涨。这与横截面动量不同，不需要与其他资产比较。",
    markets: ["futures", "crypto"],
    timeframes: ["position"],
    difficulty: 2,
    riskLevel: "medium",
    theory: {
      origin: "2012年《Journal of Financial Economics》发表",
      author: "Tobias Moskowitz, Yao Hua Ooi & Lasse Pedersen",
      authorInfo: "Moskowitz是AQR Capital Management研究总监",
      year: 2012,
      paper: "Time Series Momentum",
      paperUrl: "https://doi.org/10.1016/j.jfineco.2011.11.003",
      academicBasis: "行为金融学、趋势跟踪",
    },
    logic: {
      entry: ["计算过去12个月的累计收益", "如果收益为正，做多", "如果收益为负，做空或空仓"],
      exit: ["月末再评估，收益转负则平仓或做空"],
      positionSizing: "根据波动率调整仓位，波动率高则减仓",
      riskManagement: "目标年化波动率10-15%",
    },
    params: [
      {
        name: "回望期",
        nameEn: "Lookback",
        default: 12,
        range: "1-24",
        description: "计算收益的月数",
      },
      {
        name: "目标波动率",
        nameEn: "Target Vol",
        default: "10%",
        range: "5-20%",
        description: "目标年化波动率",
      },
    ],
    pros: ["适用于多种资产类别", "可做空获取下跌收益", "逻辑简单直观"],
    cons: ["震荡市频繁换仓", "需要期货账户做空", "滑点成本高"],
    bestPractices: {
      dos: ["在多个不相关资产上分散应用", "使用波动率调整仓位", "月度再平衡"],
      donts: ["不要只在单一资产上使用", "不要忽视做空成本"],
      tips: ["可与其他策略组合", "商品期货上效果显著"],
    },
    periodSignificance: {
      shortTerm: "1个月太短，噪音大",
      mediumTerm: "12个月是最佳回望期",
      longTerm: "超过24个月效果减弱",
      bestPeriod: "12个月回望，月度调仓",
    },
    bestFor: "管理期货CTA策略",
    bestForEn: "Managed futures/CTA strategies",
    notSuitableFor: "高波动震荡市场",
    historicalPerformance: {
      backtestPeriod: "1965-2009 (原始论文)",
      annualReturn: 14,
      sharpeRatio: 1.0,
      note: "在58种流动性期货上测试有效",
    },
    prompt:
      "时间序列动量：计算过去12个月收益，正收益做多，负收益做空，按波动率调整仓位使目标波动率为10%",
    version: "1.0",
    lastUpdated: "2025-01-20",
  },
  {
    id: "academic-03",
    name: "Carhart四因子模型",
    nameEn: "Carhart Four-Factor Model",
    category: "factor",
    subcategory: "multi-factor",
    type: "academic",
    icon: "📐",
    summary: "市场+规模+价值+动量，四因子选股",
    summaryEn: "Market + Size + Value + Momentum, four-factor stock selection",
    description:
      "Carhart在1997年将Jegadeesh-Titman的动量因子加入Fama-French三因子模型，形成四因子模型。该模型能解释大部分共同基金的收益差异。",
    markets: ["stock"],
    timeframes: ["position", "longterm"],
    difficulty: 3,
    riskLevel: "medium",
    theory: {
      origin: "1997年《Journal of Finance》发表",
      author: "Mark Carhart",
      authorInfo: "高盛资产管理前量化研究主管",
      year: 1997,
      paper: "On Persistence in Mutual Fund Performance",
      paperUrl: "https://doi.org/10.1111/j.1540-6261.1997.tb03808.x",
      academicBasis: "因子投资、资产定价",
    },
    logic: {
      entry: [
        "计算四个因子得分：市场Beta、规模(小盘)、价值(高B/M)、动量",
        "综合得分高的股票买入",
      ],
      exit: ["综合得分下降时卖出", "季度再平衡"],
      positionSizing: "按因子暴露度加权",
    },
    params: [
      {
        name: "规模权重",
        nameEn: "Size Weight",
        default: 0.25,
        range: "0-0.5",
        description: "小市值因子权重",
      },
      {
        name: "价值权重",
        nameEn: "Value Weight",
        default: 0.25,
        range: "0-0.5",
        description: "价值因子权重",
      },
      {
        name: "动量权重",
        nameEn: "Momentum Weight",
        default: 0.25,
        range: "0-0.5",
        description: "动量因子权重",
      },
    ],
    pros: ["多因子分散风险", "学术基础扎实", "可解释性强"],
    cons: ["因子可能同时失效", "数据要求高", "实现复杂"],
    bestPractices: {
      dos: ["定期更新因子数据", "监控因子暴露度", "分散持股"],
      donts: ["不要过度依赖单一因子", "不要忽视交易成本"],
      tips: ["可根据市场环境动态调整因子权重"],
    },
    periodSignificance: {
      shortTerm: "因子表现波动大",
      mediumTerm: "季度调仓效果较好",
      longTerm: "长期因子溢价更稳定",
      bestPeriod: "季度或年度再平衡",
    },
    bestFor: "长期股票投资组合管理",
    bestForEn: "Long-term equity portfolio management",
    prompt:
      "Carhart四因子策略：计算规模、价值、动量三个因子得分，综合排名买入前20%股票，季度再平衡",
    version: "1.0",
    lastUpdated: "2025-01-20",
  },

  // ========== VALUE STRATEGIES (2) ==========
  {
    id: "academic-04",
    name: "Fama-French价值因子",
    nameEn: "Fama-French Value Factor (HML)",
    category: "factor",
    subcategory: "value",
    type: "academic",
    icon: "💎",
    summary: "高账面市值比(B/M)股票组合，经典价值投资",
    summaryEn: "High book-to-market ratio portfolio, classic value investing",
    description:
      "Fama和French在1992年发现高账面市值比(B/M)的股票长期收益高于低B/M股票。这一'价值溢价'成为因子投资的基石，也是对有效市场假说的重要挑战。",
    markets: ["stock"],
    timeframes: ["longterm"],
    difficulty: 2,
    riskLevel: "medium",
    theory: {
      origin: "1992年《Journal of Finance》发表",
      author: "Eugene Fama & Kenneth French",
      authorInfo: "Fama是2013年诺贝尔经济学奖得主，被誉为'现代金融学之父'",
      year: 1992,
      paper: "The Cross-Section of Expected Stock Returns",
      paperUrl: "https://doi.org/10.1111/j.1540-6261.1992.tb04398.x",
      academicBasis: "价值投资、风险溢价、行为金融",
    },
    logic: {
      entry: ["计算所有股票的账面市值比(B/M)", "买入B/M最高的30%股票"],
      exit: ["B/M下降到中位数以下时卖出", "年度再平衡"],
      positionSizing: "市值加权或等权重",
    },
    params: [
      {
        name: "B/M阈值",
        nameEn: "B/M Threshold",
        default: "30%",
        range: "20-40%",
        description: "选取B/M排名前X%",
      },
      {
        name: "再平衡频率",
        nameEn: "Rebalance",
        default: "年度",
        range: "季度-年度",
      },
    ],
    pros: ["长期溢价显著（约5%/年）", "逻辑简单", "巴菲特等大师验证"],
    cons: ["可能长期跑输（如2010-2020成长股牛市）", "价值陷阱风险", "需要耐心"],
    bestPractices: {
      dos: ["长期持有，至少3-5年", "分散投资多只价值股", "结合质量因子避免价值陷阱"],
      donts: ["不要在成长股泡沫期焦虑", "不要买入即将破产的'便宜'股"],
      tips: ["可用PB、PE、股息率等多指标综合筛选"],
    },
    periodSignificance: {
      shortTerm: "短期波动大，可能跑输",
      mediumTerm: "1-3年可能跑输成长股",
      longTerm: "5年以上价值溢价较稳定",
      bestPeriod: "长期持有，年度再平衡",
    },
    bestFor: "长期价值投资者",
    bestForEn: "Long-term value investors",
    notSuitableFor: "追求短期收益、成长股泡沫期",
    historicalPerformance: {
      backtestPeriod: "1963-1990 (原始论文)",
      annualReturn: 5,
      note: "HML因子年化溢价约5%",
    },
    prompt:
      "Fama-French价值策略：计算所有股票的账面市值比，买入排名前30%的高B/M股票，年度再平衡",
    version: "1.0",
    lastUpdated: "2025-01-20",
  },
  {
    id: "academic-05",
    name: "Asness质量因子",
    nameEn: "AQR Quality Factor (QMJ)",
    category: "factor",
    subcategory: "quality",
    type: "academic",
    icon: "⭐",
    summary: "高盈利、低杠杆、稳定增长，买入'优质'股票",
    summaryEn: "High profitability, low leverage, stable growth - buy quality",
    description:
      "Asness等人在2019年系统定义了'质量'因子：高盈利能力、低财务杠杆、稳定的盈利增长。'Quality Minus Junk'(QMJ)因子买入高质量股票、卖出低质量股票，获得稳定溢价。",
    markets: ["stock"],
    timeframes: ["position", "longterm"],
    difficulty: 3,
    riskLevel: "low",
    theory: {
      origin: "2019年《Review of Accounting Studies》发表",
      author: "Clifford Asness, Andrea Frazzini & Lasse Pedersen",
      authorInfo: "Asness是AQR Capital Management创始人，管理超过1400亿美元",
      year: 2019,
      paper: "Quality Minus Junk",
      paperUrl: "https://doi.org/10.1007/s11142-018-9470-2",
      academicBasis: "因子投资、基本面分析",
    },
    logic: {
      entry: [
        "计算盈利能力：ROE、ROA、毛利率",
        "计算安全性：低杠杆、低Beta、低波动",
        "计算成长性：稳定的盈利增长",
        "综合得分买入前20%",
      ],
      exit: ["质量得分下降时卖出", "季度再平衡"],
    },
    params: [
      {
        name: "盈利权重",
        nameEn: "Profitability",
        default: 0.4,
        range: "0.2-0.5",
      },
      {
        name: "安全权重",
        nameEn: "Safety",
        default: 0.3,
        range: "0.2-0.4",
      },
      { name: "成长权重", nameEn: "Growth", default: 0.3, range: "0.2-0.4" },
    ],
    pros: ["熊市防御性好", "与价值因子低相关", "回撤较小"],
    cons: ["牛市可能跑输", "需要财务数据", "定义主观"],
    bestPractices: {
      dos: ["与价值因子结合使用", "关注财务数据质量", "分散投资"],
      donts: ["不要忽视估值", "不要只看单一质量指标"],
      tips: ["在熊市中质量因子表现突出", "可作为防御性配置"],
    },
    periodSignificance: {
      shortTerm: "短期效果不明显",
      mediumTerm: "熊市中防御性突出",
      longTerm: "长期稳定溢价",
      bestPeriod: "长期持有，季度再平衡",
    },
    bestFor: "追求稳健收益的投资者",
    bestForEn: "Investors seeking stable returns",
    historicalPerformance: {
      backtestPeriod: "1957-2012 (原始论文)",
      annualReturn: 4,
      maxDrawdown: 20,
      sharpeRatio: 0.8,
      note: "QMJ因子年化溢价约4%，熊市表现优异",
    },
    prompt:
      "质量因子策略：综合计算ROE、杠杆率、盈利稳定性，买入质量得分前20%的股票",
    version: "1.0",
    lastUpdated: "2025-01-20",
  },

  // ========== BEHAVIORAL STRATEGIES (2) ==========
  {
    id: "academic-06",
    name: "DeBondt-Thaler反转效应",
    nameEn: "DeBondt-Thaler Contrarian",
    category: "mean-revert",
    subcategory: "long-term-reversal",
    type: "academic",
    icon: "🔄",
    summary: "3-5年输家变赢家，长期反转效应",
    summaryEn: "3-5 year losers become winners, long-term reversal effect",
    description:
      "DeBondt和Thaler在1985年发现市场存在过度反应：过去3-5年表现最差的股票在未来3-5年表现优于市场。这一发现支持了行为金融学的'投资者过度反应'假说。",
    markets: ["stock"],
    timeframes: ["longterm"],
    difficulty: 2,
    riskLevel: "high",
    theory: {
      origin: "1985年《Journal of Finance》发表",
      author: "Werner DeBondt & Richard Thaler",
      authorInfo: "Thaler是2017年诺贝尔经济学奖得主，行为经济学奠基人",
      year: 1985,
      paper: "Does the Stock Market Overreact?",
      paperUrl: "https://doi.org/10.1111/j.1540-6261.1985.tb05004.x",
      academicBasis: "行为金融学、投资者过度反应",
    },
    logic: {
      entry: ["计算过去3-5年累计收益", "买入排名最后20%的'输家'股票"],
      exit: ["持有3-5年", "或收益排名进入前50%时卖出"],
    },
    params: [
      {
        name: "回望期",
        nameEn: "Formation Period",
        default: 36,
        range: "24-60",
        description: "月数",
      },
      { name: "持有期", nameEn: "Holding Period", default: 36, range: "24-60" },
      { name: "选股比例", nameEn: "Selection", default: "20%", range: "10-30%" },
    ],
    pros: ["学术验证有效", "与动量策略负相关", "长期超额收益"],
    cons: ["需要很长持有期", "输家股票风险高", "可能有价值陷阱"],
    bestPractices: {
      dos: ["极度分散投资", "有耐心持有3-5年", "结合基本面筛选"],
      donts: ["不要买入即将破产的股票", "不要过早卖出"],
      tips: ["可与动量策略反向配置以分散风险"],
    },
    periodSignificance: {
      shortTerm: "短期可能继续下跌",
      mediumTerm: "1-2年反转不明显",
      longTerm: "3-5年反转效应显著",
      bestPeriod: "3-5年回望和持有期",
    },
    bestFor: "超长期投资者",
    bestForEn: "Ultra long-term investors",
    notSuitableFor: "短期投资、风险厌恶者",
    historicalPerformance: {
      backtestPeriod: "1933-1980 (原始论文)",
      annualReturn: 8,
      note: "输家组合比赢家组合年化高约8%",
    },
    prompt:
      "长期反转策略：买入过去3年收益排名最后20%的股票，持有3年后再平衡",
    version: "1.0",
    lastUpdated: "2025-01-20",
  },
  {
    id: "academic-07",
    name: "Banz小市值效应",
    nameEn: "Banz Size Effect",
    category: "factor",
    subcategory: "size",
    type: "academic",
    icon: "🏢",
    summary: "小市值股票长期跑赢大盘，规模异象",
    summaryEn: "Small-cap stocks outperform over time, size anomaly",
    description:
      "Banz在1981年发现小市值股票的收益率显著高于大市值股票，即使控制了Beta风险。这一'规模效应'成为最早被发现的市场异象之一。",
    markets: ["stock"],
    timeframes: ["longterm"],
    difficulty: 1,
    riskLevel: "high",
    theory: {
      origin: "1981年《Journal of Financial Economics》发表",
      author: "Rolf Banz",
      year: 1981,
      paper: "The Relationship Between Return and Market Value of Common Stocks",
      academicBasis: "资产定价、风险溢价",
    },
    logic: {
      entry: ["按市值排序所有股票", "买入市值最小的20%股票"],
      exit: ["市值增长到中位数以上时卖出", "年度再平衡"],
    },
    params: [
      { name: "市值阈值", nameEn: "Size Threshold", default: "20%", range: "10-30%" },
      { name: "再平衡", nameEn: "Rebalance", default: "年度", range: "季度-年度" },
    ],
    pros: ["历史溢价显著", "逻辑简单", "与价值因子协同"],
    cons: ["流动性风险", "交易成本高", "近年效果减弱"],
    bestPractices: {
      dos: ["分散投资多只小盘股", "控制流动性风险", "长期持有"],
      donts: ["不要买入微型股（流动性太差）", "不要频繁交易"],
      tips: ["可与价值因子结合，买入'小盘价值股'"],
    },
    periodSignificance: {
      shortTerm: "波动大",
      mediumTerm: "可能跑输大盘",
      longTerm: "5年以上规模溢价较稳定",
      bestPeriod: "长期持有",
    },
    bestFor: "长期投资者，能承受高波动",
    bestForEn: "Long-term investors tolerant of volatility",
    historicalPerformance: {
      backtestPeriod: "1936-1975 (原始论文)",
      annualReturn: 5,
      note: "最小市值组比最大市值组年化高约5%",
    },
    prompt: "小市值策略：买入市值排名后20%的股票，年度再平衡",
    version: "1.0",
    lastUpdated: "2025-01-20",
  },

  // ========== LOW VOLATILITY / BETTING AGAINST BETA (2) ==========
  {
    id: "academic-08",
    name: "Ang低波动异象",
    nameEn: "Low Volatility Anomaly",
    category: "factor",
    subcategory: "low-volatility",
    type: "academic",
    icon: "📉",
    summary: "低波动股票收益更高，违反风险收益正相关假设",
    summaryEn: "Low volatility stocks outperform, contradicting risk-return tradeoff",
    description:
      "Ang等人在2006年发现一个反直觉的现象：低波动率股票的收益竟然高于高波动率股票。这挑战了'高风险高回报'的传统金融理论，可能源于投资者对'彩票型'股票的偏好。",
    markets: ["stock"],
    timeframes: ["position", "longterm"],
    difficulty: 2,
    riskLevel: "low",
    theory: {
      origin: "2006年《Journal of Finance》发表",
      author: "Andrew Ang, Robert Hodrick, Yuhang Xing & Xiaoyan Zhang",
      year: 2006,
      paper: "The Cross-Section of Volatility and Expected Returns",
      academicBasis: "行为金融学、彩票偏好、杠杆约束",
    },
    logic: {
      entry: ["计算所有股票过去12个月的波动率", "买入波动率最低的20%股票"],
      exit: ["波动率上升到中位数以上时卖出", "月度再平衡"],
    },
    params: [
      { name: "回望期", nameEn: "Lookback", default: 12, range: "6-24" },
      { name: "选股比例", nameEn: "Selection", default: "20%", range: "10-30%" },
    ],
    pros: ["风险调整后收益优秀", "回撤小", "防御性强"],
    cons: ["牛市可能跑输", "需要频繁调仓", "可能错过大涨股票"],
    bestPractices: {
      dos: ["月度监控波动率", "分散投资", "作为防御性配置"],
      donts: ["不要期望在牛市中跑赢", "不要集中持股"],
      tips: ["可用Beta或特质波动率替代总波动率", "与质量因子高度相关"],
    },
    periodSignificance: {
      shortTerm: "防御性在下跌中体现",
      mediumTerm: "震荡市表现好",
      longTerm: "长期风险调整收益优秀",
      bestPeriod: "月度调仓，长期持有",
    },
    bestFor: "追求稳健、低回撤的投资者",
    bestForEn: "Risk-averse investors seeking stable returns",
    historicalPerformance: {
      backtestPeriod: "1963-2000 (原始论文)",
      sharpeRatio: 0.9,
      note: "低波动组合夏普比率显著高于高波动组合",
    },
    prompt: "低波动策略：计算过去12个月波动率，买入波动率最低的20%股票，月度再平衡",
    version: "1.0",
    lastUpdated: "2025-01-20",
  },
  {
    id: "academic-09",
    name: "Frazzini对赌Beta",
    nameEn: "Betting Against Beta (BAB)",
    category: "factor",
    subcategory: "low-beta",
    type: "academic",
    icon: "🎰",
    summary: "做多低Beta股票、做空高Beta股票，杠杆中性",
    summaryEn: "Long low-beta, short high-beta, leverage neutral",
    description:
      "Frazzini和Pedersen在2014年提出'对赌Beta'策略：由于投资者杠杆受限，他们偏好高Beta股票以获取高收益，导致高Beta被高估、低Beta被低估。做多低Beta、做空高Beta可获得稳定溢价。",
    markets: ["stock", "futures"],
    timeframes: ["position"],
    difficulty: 3,
    riskLevel: "medium",
    theory: {
      origin: "2014年《Journal of Financial Economics》发表",
      author: "Andrea Frazzini & Lasse Pedersen",
      authorInfo: "两人都是AQR Capital的研究员",
      year: 2014,
      paper: "Betting Against Beta",
      paperUrl: "https://doi.org/10.1016/j.jfineco.2013.10.005",
      academicBasis: "杠杆约束、资产定价",
    },
    logic: {
      entry: [
        "计算所有股票的Beta",
        "做多Beta最低的组",
        "做空Beta最高的组",
        "杠杆调整使组合Beta为1",
      ],
      exit: ["月度再平衡"],
      positionSizing: "按Beta倒数调整杠杆",
    },
    params: [
      { name: "估计窗口", nameEn: "Estimation Window", default: 12, range: "6-36" },
      { name: "再平衡", nameEn: "Rebalance", default: "月度", range: "月度-季度" },
    ],
    pros: ["市场中性", "与传统因子低相关", "夏普比率高"],
    cons: ["需要做空", "杠杆操作复杂", "做空成本"],
    bestPractices: {
      dos: ["严格控制杠杆", "月度再平衡", "监控做空成本"],
      donts: ["不要忽视做空风险", "不要过度杠杆"],
      tips: ["可在期货市场更容易实现做空"],
    },
    periodSignificance: {
      shortTerm: "月度表现稳定",
      mediumTerm: "与市场走势相关性低",
      longTerm: "长期稳定溢价",
      bestPeriod: "月度再平衡",
    },
    bestFor: "对冲基金、量化投资者",
    bestForEn: "Hedge funds, quantitative investors",
    historicalPerformance: {
      backtestPeriod: "1926-2012 (原始论文)",
      annualReturn: 9,
      sharpeRatio: 0.78,
      note: "BAB因子月均收益约0.73%",
    },
    prompt:
      "对赌Beta策略：计算股票Beta，做多低Beta组、做空高Beta组，调整杠杆使组合Beta为1",
    version: "1.0",
    lastUpdated: "2025-01-20",
  },

  // ========== YIELD CURVE / MACRO (1) ==========
  {
    id: "academic-10",
    name: "Harvey收益率曲线",
    nameEn: "Harvey Yield Curve Indicator",
    category: "composite",
    subcategory: "macro",
    type: "academic",
    icon: "📈",
    summary: "收益率曲线倒挂预测衰退，倒挂时减仓",
    summaryEn: "Yield curve inversion predicts recession, reduce exposure when inverted",
    description:
      "Campbell Harvey在1988年发现美国国债收益率曲线倒挂（短期利率高于长期利率）可以预测经济衰退。这一指标在过去50年准确预测了每次衰退，被称为'衰退的水晶球'。",
    markets: ["stock"],
    timeframes: ["longterm"],
    difficulty: 1,
    riskLevel: "low",
    theory: {
      origin: "1988年博士论文，1989年正式发表",
      author: "Campbell Harvey",
      authorInfo: "杜克大学金融学教授，前美国金融学会主席",
      year: 1988,
      paper: "The Real Term Structure and Consumption Growth",
      academicBasis: "宏观经济、期限结构",
    },
    logic: {
      entry: ["监控10年期和2年期国债收益率差", "正利差时满仓股票"],
      exit: ["利差转负（倒挂）时减仓50%或更多", "衰退结束后恢复仓位"],
    },
    params: [
      { name: "长端利率", nameEn: "Long Rate", default: "10Y", range: "10Y" },
      { name: "短端利率", nameEn: "Short Rate", default: "2Y", range: "2Y-3M" },
      { name: "减仓比例", nameEn: "Reduction", default: "50%", range: "30-70%" },
    ],
    pros: ["简单有效", "预测准确率高", "避免大熊市"],
    cons: ["信号稀少", "可能提前很久（1-2年）", "可能错过反弹"],
    bestPractices: {
      dos: ["结合其他指标确认", "耐心等待信号", "逐步减仓"],
      donts: ["不要倒挂后立即清仓", "不要忽视其他风险信号"],
      tips: ["倒挂后通常12-18个月才会衰退", "可用3个月期国债替代2年期"],
    },
    periodSignificance: {
      shortTerm: "日常波动无意义",
      mediumTerm: "持续倒挂1-3个月才有意义",
      longTerm: "预测1-2年后的衰退",
      bestPeriod: "月度监控，长期信号",
    },
    bestFor: "长期资产配置、风险管理",
    bestForEn: "Long-term asset allocation, risk management",
    historicalPerformance: {
      backtestPeriod: "1968-2019",
      note: "准确预测了过去7次衰退，无假信号",
    },
    riskWarning: "收益率曲线倒挂后平均12-18个月才会出现衰退，不宜过早行动。",
    prompt:
      "收益率曲线策略：监控10年期-2年期国债利差，利差转负时将股票仓位减少50%",
    version: "1.0",
    lastUpdated: "2025-01-20",
  },
];

// Export all academic strategies
export default academicStrategies;
